#!/usr/bin/env python3
import os
import sys
import helpers
from analyzer import Analyzer
from termcolor import colored
def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @username")
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    screen_name = sys.argv[1].strip('@')
    tweets = helpers.get_user_timeline(screen_name, 50)
    if tweets == None:
        sys.exit("User is private or doesn't exist")
    for tweet in tweets:
        count = analyzer.analyze(tweet)
        if count > 0.0:
            print(colored("{} {}".format(count, tweet), "green"))
        elif count < 0.0:
            print(colored("{} {}".format(count, tweet), "red"))
        else:
            print(colored("{} {}".format(count, tweet), "yellow"))
if __name__ == "__main__":
    main()
    
    
    
